/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Bron Zilar
 */
public class FKonfiguracijaServera extends javax.swing.JDialog {

    /**
     * Creates new form FKonfiguracijaServera
     */
    public FKonfiguracijaServera(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        try {
            srediFormu();
        } catch (IOException ex) {
            Logger.getLogger(FKonfiguracijaServera.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jlblServerSocket = new javax.swing.JLabel();
        jtxtServerSocket = new javax.swing.JTextField();
        jbtnIzadji = new javax.swing.JButton();
        jbtnSacuvaj = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Konfiguracija servera");

        jlblServerSocket.setText("ServerSocket broj porta:");

        jbtnIzadji.setText("Izadji");
        jbtnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzadjiActionPerformed(evt);
            }
        });

        jbtnSacuvaj.setText("Sacuvaj");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblServerSocket)
                    .addComponent(jbtnIzadji))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 163, Short.MAX_VALUE)
                        .addComponent(jbtnSacuvaj))
                    .addComponent(jtxtServerSocket))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtServerSocket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblServerSocket))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnIzadji)
                    .addComponent(jbtnSacuvaj))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzadjiActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnIzadjiActionPerformed

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        FileInputStream in = null;
        try {
            in = new FileInputStream("db.properties");
            Properties props = new Properties();
            props.load(in);
            in.close();
            FileOutputStream out = new FileOutputStream("db.properties");
            Integer ss = 0;
            try {
            ss = Integer.parseInt(jtxtServerSocket.getText().trim());
            if(ss<0 || ss>65535) {
                props.setProperty("driver", "com.mysql.jdbc.Driver");
                props.setProperty("url", "jdbc:mysql://localhost:3306/bioskop");
                props.setProperty("user", "root");
                props.setProperty("password", "");
                props.setProperty("serverSocket", "9000");
                props.store(out, null);
                out.close();
                JOptionPane.showMessageDialog(this, "Broj porta mora biti u opsegu 0-65535", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
            } catch(NumberFormatException ex) {
                props.setProperty("driver", "com.mysql.jdbc.Driver");
                props.setProperty("url", "jdbc:mysql://localhost:3306/bioskop");
                props.setProperty("user", "root");
                props.setProperty("password", "");
                props.setProperty("serverSocket", "9000");
                props.store(out, null);
                out.close();
                JOptionPane.showMessageDialog(this, "Port serverskog soketa mora biti ceo broj.", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
            props.setProperty("serverSocket", ss.toString());
            props.store(out, null);
            out.close();
            JOptionPane.showMessageDialog(this, "Uspesno promenjen parametar za konfiguraciju servera.");
            this.setVisible(false);
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Doslo je do greske prilikom cuvanja promenjenih parametara", "Greska", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FKonfiguracijaServera.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Doslo je do greske prilikom cuvanja promenjenih parametara", "Greska", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FKonfiguracijaServera.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                in.close();
            } catch (IOException ex) {
                Logger.getLogger(FKonfiguracijaServera.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JButton jbtnIzadji;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JLabel jlblServerSocket;
    private javax.swing.JTextField jtxtServerSocket;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() throws FileNotFoundException, IOException {
        FileInputStream in=new FileInputStream("db.properties");
        Properties props=new Properties();
        props.load(in);
        Integer serverSoket = Integer.parseInt(props.getProperty("serverSocket"));
        jtxtServerSocket.setText(serverSoket.toString());
        setLocationRelativeTo(null);
    }
}
