/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Korisnik;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author Bron Zilar
 */
public class FGlavnaFormaKorisnik extends javax.swing.JFrame {

    private final Korisnik k;
    
    /**
     * Creates new form FGlavnaFormaKorisnik
     */
    public FGlavnaFormaKorisnik(Korisnik korisnik) {
        initComponents();
        setLocationRelativeTo(null);
        k = korisnik;
        setTitle("Dobrodosli " + k.getIme() + " " + k.getPrezime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFilm = new javax.swing.JMenu();
        jMenuItemFilmovi = new javax.swing.JMenuItem();
        jMenuProjekcija = new javax.swing.JMenu();
        jMenuItemProjekcije = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuFilm.setText("Film");

        jMenuItemFilmovi.setText("Pretraga filmova");
        jMenuItemFilmovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFilmoviActionPerformed(evt);
            }
        });
        jMenuFilm.add(jMenuItemFilmovi);

        jMenuBar1.add(jMenuFilm);

        jMenuProjekcija.setText("Projekcija");

        jMenuItemProjekcije.setText("Pretraga projekcija");
        jMenuItemProjekcije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProjekcijeActionPerformed(evt);
            }
        });
        jMenuProjekcija.add(jMenuItemProjekcije);

        jMenuBar1.add(jMenuProjekcija);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemFilmoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFilmoviActionPerformed
        try {
            JDialog forma = new FPretragaFilma(this, true, FormaMod.FORMA_PRETRAGA);
            forma.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FGlavnaFormaKorisnik.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuItemFilmoviActionPerformed

    private void jMenuItemProjekcijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProjekcijeActionPerformed
        try {
            JDialog forma = new FPretragaProjekcije(this, true, k);
            forma.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FGlavnaFormaKorisnik.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemProjekcijeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFilm;
    private javax.swing.JMenuItem jMenuItemFilmovi;
    private javax.swing.JMenuItem jMenuItemProjekcije;
    private javax.swing.JMenu jMenuProjekcija;
    // End of variables declaration//GEN-END:variables
}
