/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Projekcija;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import kontroler.Kontroler;
import model.ProjekcijaTableModel;

/**
 *
 * @author Bron Zilar
 */
public class FPretragaProjekcije extends javax.swing.JDialog {

    /**
     * Creates new form FPretragaProjekcije
     */
    public FPretragaProjekcije(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();
        
        if(parent instanceof FGlavnaFormaKorisnik) {
            jbtnObrisi.setVisible(false);
        }
        
        setLocationRelativeTo(null);
        
        pripremiFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblPretraziPoImenu = new javax.swing.JLabel();
        jtxtPretraziPoImenuFilma = new javax.swing.JTextField();
        jbtnPretraziPoImenuFilma = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblProjekcije = new javax.swing.JTable();
        jbtnIzadji = new javax.swing.JButton();
        jbtnDetalji = new javax.swing.JButton();
        jbtnObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlblPretraziPoImenu.setText("Pretrazi po imenu filma:");

        jbtnPretraziPoImenuFilma.setText("Pretrazi");
        jbtnPretraziPoImenuFilma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPretraziPoImenuFilmaActionPerformed(evt);
            }
        });

        jtblProjekcije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblProjekcije);

        jbtnIzadji.setText("Izadji");
        jbtnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzadjiActionPerformed(evt);
            }
        });

        jbtnDetalji.setText("Detalji");
        jbtnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDetaljiActionPerformed(evt);
            }
        });

        jbtnObrisi.setText("Obrisi");
        jbtnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnIzadji)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jbtnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblPretraziPoImenu, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtPretraziPoImenuFilma)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnPretraziPoImenuFilma, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPretraziPoImenu)
                    .addComponent(jtxtPretraziPoImenuFilma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPretraziPoImenuFilma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jbtnIzadji))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnObrisi)
                            .addComponent(jbtnDetalji))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzadjiActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnIzadjiActionPerformed

    private void jbtnPretraziPoImenuFilmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPretraziPoImenuFilmaActionPerformed
        String naziv = jtxtPretraziPoImenuFilma.getText().trim();
        TableModel tm = jtblProjekcije.getModel();
        ProjekcijaTableModel ptm = (ProjekcijaTableModel) tm;
        ptm.pretraziProjekcijePoNazivuFilma(naziv);
        if(jtblProjekcije.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje projekcije po zadatoj vrednosti!");
        }
    }//GEN-LAST:event_jbtnPretraziPoImenuFilmaActionPerformed

    private void jbtnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDetaljiActionPerformed
        int selektovanRed = jtblProjekcije.getSelectedRow();
        TableModel tm = jtblProjekcije.getModel();
        ProjekcijaTableModel ptm = (ProjekcijaTableModel) tm;
        Long id = (Long) ptm.getValueAt(selektovanRed, 0);
        Projekcija projekcija = ptm.nadjiProjekciju(id);
        JDialog forma = new FProjekcijaDetalji(this, true, projekcija);
        forma.setVisible(true);
        
    }//GEN-LAST:event_jbtnDetaljiActionPerformed

    private void jbtnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiActionPerformed
        int selektovanRed = jtblProjekcije.getSelectedRow();
        TableModel tm = jtblProjekcije.getModel();
        ProjekcijaTableModel ptm = (ProjekcijaTableModel) tm;
        Long id = (Long) ptm.getValueAt(selektovanRed, 0);
        try {
            if(Kontroler.getInstanca().obrisiProjekciju(id)) {
                pripremiFormu();
                JOptionPane.showMessageDialog(this, "Projekcija je uspesno obrisana");
            } else {
                JOptionPane.showMessageDialog(this, "Doslo je do greske prilikom brisanja, projekcijan nije obrisana");
            }
        } catch (Exception ex) {
            Logger.getLogger(FPretragaProjekcije.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnObrisiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDetalji;
    private javax.swing.JButton jbtnIzadji;
    private javax.swing.JButton jbtnObrisi;
    private javax.swing.JButton jbtnPretraziPoImenuFilma;
    private javax.swing.JLabel jlblPretraziPoImenu;
    private javax.swing.JTable jtblProjekcije;
    private javax.swing.JTextField jtxtPretraziPoImenuFilma;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() throws Exception {
        List<Projekcija> projekcije = Kontroler.getInstanca().vratiSveProjekcije();
        jtblProjekcije.setModel(new ProjekcijaTableModel(projekcije));
    }
}
