/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Film;
import domen.Zanr;
import java.util.ArrayList;
import java.util.List;
import model.FilmTableModel;

/**
 *
 * @author Bron Zilar
 */
public class FPretragaFilma extends javax.swing.JDialog {

    /**
     * Creates new form FPretragaFilma
     */
    public FPretragaFilma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(null);
        
        pripremiFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblFilmovi = new javax.swing.JTable();
        jlblFiltriraj = new javax.swing.JLabel();
        jcomboFiltriraj = new javax.swing.JComboBox<>();
        jlblPretrazi = new javax.swing.JLabel();
        jtxtPretrazi = new javax.swing.JTextField();
        jbtnPretrazi = new javax.swing.JButton();
        jbtnDetalji = new javax.swing.JButton();
        jbtnIzadji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtblFilmovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblFilmovi);

        jlblFiltriraj.setText("Filtriraj po zanru:");

        jcomboFiltriraj.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlblPretrazi.setText("Pretrazi po imenu:");

        jbtnPretrazi.setText("Pretrazi");

        jbtnDetalji.setText("Detalji");

        jbtnIzadji.setText("Izadji");
        jbtnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzadjiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlblPretrazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblFiltriraj, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcomboFiltriraj, 0, 284, Short.MAX_VALUE)
                            .addComponent(jtxtPretrazi))
                        .addGap(44, 44, 44)
                        .addComponent(jbtnPretrazi)
                        .addGap(196, 196, 196))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnIzadji)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnDetalji)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblFiltriraj, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomboFiltriraj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPretrazi)
                    .addComponent(jtxtPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPretrazi))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDetalji)
                    .addComponent(jbtnIzadji))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzadjiActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnIzadjiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDetalji;
    private javax.swing.JButton jbtnIzadji;
    private javax.swing.JButton jbtnPretrazi;
    private javax.swing.JComboBox<Object> jcomboFiltriraj;
    private javax.swing.JLabel jlblFiltriraj;
    private javax.swing.JLabel jlblPretrazi;
    private javax.swing.JTable jtblFilmovi;
    private javax.swing.JTextField jtxtPretrazi;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() {
        popuniZanrove();
        
        List<Film> filmovi = new ArrayList<>();
        jtblFilmovi.setModel(new FilmTableModel(filmovi));
    }

    private void popuniZanrove() {
        jcomboFiltriraj.removeAllItems();
        
        jcomboFiltriraj.addItem(Zanr.AKCIJA);
        jcomboFiltriraj.addItem(Zanr.DOKUMENTARNI);
        jcomboFiltriraj.addItem(Zanr.DRAMA);
        jcomboFiltriraj.addItem(Zanr.HOROR);
        jcomboFiltriraj.addItem(Zanr.KOMEDIJA);
        jcomboFiltriraj.addItem(Zanr.MISTERIJA);
        jcomboFiltriraj.addItem(Zanr.NAUCNA_FANTASTIKA);
        jcomboFiltriraj.addItem(Zanr.TRILER);
    }

}
