/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Film;
import domen.Zanr;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.TableModel;
import kontroler.Kontroler;
import model.FilmTableModel;

/**
 *
 * @author Bron Zilar
 */
public class FPretragaFilma extends javax.swing.JDialog {

    /**
     * Creates new form FPretragaFilma
     */
    public FPretragaFilma(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(null);
        
        pripremiFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblFilmovi = new javax.swing.JTable();
        jlblPretraziPoZanru = new javax.swing.JLabel();
        jcomboPretraziPoZanru = new javax.swing.JComboBox<>();
        jlblPretraziPoImenu = new javax.swing.JLabel();
        jtxtPretraziPoImenu = new javax.swing.JTextField();
        jbtnPretraziPoImenu = new javax.swing.JButton();
        jbtnDetalji = new javax.swing.JButton();
        jbtnIzadji = new javax.swing.JButton();
        jbtnPretraziPoZanru = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtblFilmovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblFilmovi);

        jlblPretraziPoZanru.setText("Pretrazi po zanru:");

        jcomboPretraziPoZanru.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlblPretraziPoImenu.setText("Pretrazi po imenu:");

        jbtnPretraziPoImenu.setText("Pretrazi po imenu");
        jbtnPretraziPoImenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPretraziPoImenuActionPerformed(evt);
            }
        });

        jbtnDetalji.setText("Detalji");
        jbtnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDetaljiActionPerformed(evt);
            }
        });

        jbtnIzadji.setText("Izadji");
        jbtnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzadjiActionPerformed(evt);
            }
        });

        jbtnPretraziPoZanru.setText("Pretrazi po zanru");
        jbtnPretraziPoZanru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPretraziPoZanruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlblPretraziPoImenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblPretraziPoZanru, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcomboPretraziPoZanru, 0, 284, Short.MAX_VALUE)
                            .addComponent(jtxtPretraziPoImenu))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnPretraziPoImenu, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jbtnPretraziPoZanru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(134, 134, 134))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnIzadji)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnDetalji)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPretraziPoZanru, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomboPretraziPoZanru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPretraziPoZanru))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPretraziPoImenu)
                    .addComponent(jtxtPretraziPoImenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPretraziPoImenu))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDetalji)
                    .addComponent(jbtnIzadji))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzadjiActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnIzadjiActionPerformed

    private void jbtnPretraziPoZanruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPretraziPoZanruActionPerformed
        Zanr zanr = (Zanr) jcomboPretraziPoZanru.getSelectedItem();
        TableModel tm = jtblFilmovi.getModel();
        FilmTableModel ftm = (FilmTableModel) tm;
        ftm.pretraziFilmovePoZanru(zanr);
    }//GEN-LAST:event_jbtnPretraziPoZanruActionPerformed

    private void jbtnPretraziPoImenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPretraziPoImenuActionPerformed
        String naziv = jtxtPretraziPoImenu.getText().trim();
        TableModel tm = jtblFilmovi.getModel();
        FilmTableModel ftm = (FilmTableModel) tm;
        ftm.pretraziFilmovePoImenu(naziv);
    }//GEN-LAST:event_jbtnPretraziPoImenuActionPerformed

    private void jbtnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDetaljiActionPerformed
        int selektovanRed = jtblFilmovi.getSelectedRow();
        TableModel tm = jtblFilmovi.getModel();
        FilmTableModel ftm = (FilmTableModel) tm;
        Long id = (Long) ftm.getValueAt(selektovanRed, 0);
        Film film = ftm.nadjiFilm(id);
    }//GEN-LAST:event_jbtnDetaljiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDetalji;
    private javax.swing.JButton jbtnIzadji;
    private javax.swing.JButton jbtnPretraziPoImenu;
    private javax.swing.JButton jbtnPretraziPoZanru;
    private javax.swing.JComboBox<Object> jcomboPretraziPoZanru;
    private javax.swing.JLabel jlblPretraziPoImenu;
    private javax.swing.JLabel jlblPretraziPoZanru;
    private javax.swing.JTable jtblFilmovi;
    private javax.swing.JTextField jtxtPretraziPoImenu;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() throws Exception {
        popuniZanrove();
        
        List<Film> filmovi = Kontroler.getInstanca().vratiSveFilmove();
        jtblFilmovi.setModel(new FilmTableModel(filmovi));
    }

    private void popuniZanrove() {
        jcomboPretraziPoZanru.removeAllItems();
        
        jcomboPretraziPoZanru.addItem(Zanr.AKCIJA);
        jcomboPretraziPoZanru.addItem(Zanr.DOKUMENTARNI);
        jcomboPretraziPoZanru.addItem(Zanr.DRAMA);
        jcomboPretraziPoZanru.addItem(Zanr.HOROR);
        jcomboPretraziPoZanru.addItem(Zanr.KOMEDIJA);
        jcomboPretraziPoZanru.addItem(Zanr.MISTERIJA);
        jcomboPretraziPoZanru.addItem(Zanr.NAUCNA_FANTASTIKA);
        jcomboPretraziPoZanru.addItem(Zanr.TRILER);
    }

}
