/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Korisnik;
import domen.Status;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;
import util.Operacije;

/**
 *
 * @author Bron Zilar
 */
public class FGlavnaFormaKorisnik extends javax.swing.JFrame {

    private final Korisnik k;
    
    /**
     * Creates new form FGlavnaFormaKorisnik
     */
    public FGlavnaFormaKorisnik(Korisnik korisnik) {
        initComponents();
        setLocationRelativeTo(null);
        k = korisnik;
        setTitle("Dobrodosli " + k.getIme() + " " + k.getPrezime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFilm = new javax.swing.JMenu();
        jMenuItemFilmovi = new javax.swing.JMenuItem();
        jMenuProjekcija = new javax.swing.JMenu();
        jMenuItemProjekcije = new javax.swing.JMenuItem();
        jMenuRezervacija = new javax.swing.JMenu();
        jMenuItemRezervacije = new javax.swing.JMenuItem();
        jMenuKrajRada = new javax.swing.JMenu();
        jMenuItemOdjava = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuFilm.setText("Film");

        jMenuItemFilmovi.setText("Pretraga filmova");
        jMenuItemFilmovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFilmoviActionPerformed(evt);
            }
        });
        jMenuFilm.add(jMenuItemFilmovi);

        jMenuBar1.add(jMenuFilm);

        jMenuProjekcija.setText("Projekcija");

        jMenuItemProjekcije.setText("Pretraga projekcija");
        jMenuItemProjekcije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProjekcijeActionPerformed(evt);
            }
        });
        jMenuProjekcija.add(jMenuItemProjekcije);

        jMenuBar1.add(jMenuProjekcija);

        jMenuRezervacija.setText("Rezervacija");

        jMenuItemRezervacije.setText("Pretraga rezervacija");
        jMenuItemRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRezervacijeActionPerformed(evt);
            }
        });
        jMenuRezervacija.add(jMenuItemRezervacije);

        jMenuBar1.add(jMenuRezervacija);

        jMenuKrajRada.setText("Kraj rada");

        jMenuItemOdjava.setText("Odjavi se");
        jMenuItemOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOdjavaActionPerformed(evt);
            }
        });
        jMenuKrajRada.add(jMenuItemOdjava);

        jMenuBar1.add(jMenuKrajRada);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemFilmoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFilmoviActionPerformed
        try {
            JDialog forma = new FPretragaFilma(this, true, FormaMod.FORMA_PRETRAGA);
            forma.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FGlavnaFormaKorisnik.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuItemFilmoviActionPerformed

    private void jMenuItemProjekcijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProjekcijeActionPerformed
        try {
            JDialog forma = new FPretragaProjekcije(this, true, k);
            forma.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FGlavnaFormaKorisnik.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemProjekcijeActionPerformed

    private void jMenuItemRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRezervacijeActionPerformed
        try {
            JDialog forma = new FPretragaRezervacija(this, true, k);
            forma.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FGlavnaFormaKorisnik.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemRezervacijeActionPerformed

    private void jMenuItemOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOdjavaActionPerformed
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.ODJAVA);
        kz.setParametar(k);
        try {
            Kontroler.getInstanca().posaljiZahtev(kz);
            ServerskiOdgovor so = Kontroler.getInstanca().primiOdgovor();
            if(so.getStatus().equals(Status.GRESKA)) {
                JOptionPane.showMessageDialog(this, "Doslo je do greske. Sistem ne moze da vas odjavi");
                return;
            }
        } catch (IOException ex) {
            Logger.getLogger(FGlavnaFormaKorisnik.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FGlavnaFormaKorisnik.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        new FPrijava().setVisible(true);
    }//GEN-LAST:event_jMenuItemOdjavaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFilm;
    private javax.swing.JMenuItem jMenuItemFilmovi;
    private javax.swing.JMenuItem jMenuItemOdjava;
    private javax.swing.JMenuItem jMenuItemProjekcije;
    private javax.swing.JMenuItem jMenuItemRezervacije;
    private javax.swing.JMenu jMenuKrajRada;
    private javax.swing.JMenu jMenuProjekcija;
    private javax.swing.JMenu jMenuRezervacija;
    // End of variables declaration//GEN-END:variables
}
