/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;

/**
 *
 * @author Bron Zilar
 */
public class FGlavnaFormaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FGlavnaFormaAdmin
     */
    public FGlavnaFormaAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        //setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFilm = new javax.swing.JMenu();
        jMenuItemPretragaFilmova = new javax.swing.JMenuItem();
        jMenuItemNoviFilm = new javax.swing.JMenuItem();
        jMenuProjekcija = new javax.swing.JMenu();
        jMenuItemPretragaProjekcija = new javax.swing.JMenuItem();
        jMenuItemNovaProjekcija = new javax.swing.JMenuItem();
        jMenuKonfiguracija = new javax.swing.JMenu();
        jMenuItemKonfiguracija = new javax.swing.JMenuItem();
        jMenuKrajRada = new javax.swing.JMenu();
        jMenuItemOdjava = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator");

        jMenuFilm.setText("Film");

        jMenuItemPretragaFilmova.setText("Pretraga filmova");
        jMenuItemPretragaFilmova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPretragaFilmovaActionPerformed(evt);
            }
        });
        jMenuFilm.add(jMenuItemPretragaFilmova);

        jMenuItemNoviFilm.setText("Novi film");
        jMenuItemNoviFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNoviFilmActionPerformed(evt);
            }
        });
        jMenuFilm.add(jMenuItemNoviFilm);

        jMenuBar1.add(jMenuFilm);

        jMenuProjekcija.setText("Projekcija");

        jMenuItemPretragaProjekcija.setText("Pretraga projekcija");
        jMenuItemPretragaProjekcija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPretragaProjekcijaActionPerformed(evt);
            }
        });
        jMenuProjekcija.add(jMenuItemPretragaProjekcija);

        jMenuItemNovaProjekcija.setText("Nova projekcija");
        jMenuItemNovaProjekcija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovaProjekcijaActionPerformed(evt);
            }
        });
        jMenuProjekcija.add(jMenuItemNovaProjekcija);

        jMenuBar1.add(jMenuProjekcija);

        jMenuKonfiguracija.setText("Konfiguracija");

        jMenuItemKonfiguracija.setText("Konfiguracija ip adrese i porta");
        jMenuItemKonfiguracija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKonfiguracijaActionPerformed(evt);
            }
        });
        jMenuKonfiguracija.add(jMenuItemKonfiguracija);

        jMenuBar1.add(jMenuKonfiguracija);

        jMenuKrajRada.setText("Kraj rada");

        jMenuItemOdjava.setText("Odjavi se");
        jMenuItemOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOdjavaActionPerformed(evt);
            }
        });
        jMenuKrajRada.add(jMenuItemOdjava);

        jMenuBar1.add(jMenuKrajRada);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNoviFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNoviFilmActionPerformed
        try {
            JDialog forma = new FFilm(this, true);
            forma.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FGlavnaFormaAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemNoviFilmActionPerformed

    private void jMenuItemPretragaFilmovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPretragaFilmovaActionPerformed
        try {
            JDialog forma = new FPretragaFilma(this, true, FormaMod.FORMA_PRETRAGA);
            forma.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FGlavnaFormaAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemPretragaFilmovaActionPerformed

    private void jMenuItemNovaProjekcijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNovaProjekcijaActionPerformed
        try {
            JDialog forma = new FProjekcija(this, true);
            forma.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FGlavnaFormaAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemNovaProjekcijaActionPerformed

    private void jMenuItemPretragaProjekcijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPretragaProjekcijaActionPerformed
        try {
            JDialog forma = new FPretragaProjekcije(this, true, null);
            forma.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FGlavnaFormaAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemPretragaProjekcijaActionPerformed

    private void jMenuItemOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOdjavaActionPerformed
        this.setVisible(false);
        new FPrijava().setVisible(true);
    }//GEN-LAST:event_jMenuItemOdjavaActionPerformed

    private void jMenuItemKonfiguracijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKonfiguracijaActionPerformed
        JDialog forma = new FKonfiguracija(this, true);
        forma.setVisible(true);
    }//GEN-LAST:event_jMenuItemKonfiguracijaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFilm;
    private javax.swing.JMenuItem jMenuItemKonfiguracija;
    private javax.swing.JMenuItem jMenuItemNovaProjekcija;
    private javax.swing.JMenuItem jMenuItemNoviFilm;
    private javax.swing.JMenuItem jMenuItemOdjava;
    private javax.swing.JMenuItem jMenuItemPretragaFilmova;
    private javax.swing.JMenuItem jMenuItemPretragaProjekcija;
    private javax.swing.JMenu jMenuKonfiguracija;
    private javax.swing.JMenu jMenuKrajRada;
    private javax.swing.JMenu jMenuProjekcija;
    // End of variables declaration//GEN-END:variables
}
